apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  labels:
    app: hello-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000=
      nodePort: 30000 # Porta externa para acesso (http://localhost:30000)
      protocol: TCP
  selector:
    app: hello-app